### ISSUE TITLE
PII is hidden error clicking login 

### ISSUE THREAD

**Issue by kristophor** [okta/samples-aspnetcore#13]
FormatException: The format of value '18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64/X64 okta-aspnet/1.0.0' is invalid.
System.Net.Http.Headers.HttpHeaderParser.ParseValue(string value, object storeValue, ref int index)

IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()

**Comment by phi1ipp** [comment]
+1 
It's very annoying, please fix the project

**Comment by laura-rodriguez** [comment]
Hi @phi1ipp,

Have you updated your `Okta.AspNetCore` package? This issue was fixed in the  version [`1.1.1`](Okta.AspNetCore) .
Let me know if it helps.

**Comment by phi1ipp** [comment]
Hi @laura-rodriguez,

Sure I updated, I meant it'd be nice if the project itself would refer to all latest versions of Okta libraries

**Comment by laura-rodriguez** [comment]
I agree with you @phi1ipp. Our samples need to refer to the latest versions.
It's something we are going to do soon, thanks for bringing this up! 👍 
As you were able to solve this, I'll close this issue and we will continue tracking the out-of-date packages on #11.
