### ISSUE TITLE
Appsettings Additional middleware configuration

### ISSUE THREAD

**Issue by andrewryan-andie** [okta/samples-aspnetcore#16]
In [QuickStart](https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnetcore) example for .netcore this is given appsettings section

OktaDomain = Configuration["Okta:Domain"],
ClientId = Configuration["Okta:ClientId"],

```
this yields to this xml section:
"Okta": {
    "ClientId": "xxxx",
    "ClientSecret": "xxxx",
    "Domain": "xxxx" //Configuration["Okta:Domain"]
  }

```
but in appsettings the section is [here](https://github.com/okta/samples-aspnetcore/blob/master/okta-hosted-login/okta-aspnetcore-mvc-example/appsettings.json) shows this xml section as:

```
"Okta": {
    "ClientId": "{ClientId}",
    "ClientSecret": "{ClientSecret}",
    "OktaDomain": "https://{yourOktaDomain}.com" //for this the C# code should be Configuration["Okta:OktaDomain"]
  }
```

**Comment by laura-rodriguez** [comment]
Hi @andrewryan-andie! Not sure if I follow you. Can you tell me what are you expecting to see in the `appsettings.json`?
The example looks correct to me. Anything you define in the `appsettings.json` can be used in your code via the Configuration pattern:
```
var oktaDomain = Configuration["Okta:Domain"];
```
Thanks!

**Comment by laura-rodriguez** [comment]
Ah! you're talking about `Domain` is not matching with `OktaDomain` right? Yep, it definitely has to be fixed! Thanks @andrewryan-andie

**Comment by laura-rodriguez** [comment]
Fixed in .NET quickstart.
