### ISSUE TITLE
Port through dotnet core cli 

### ISSUE THREAD

**Issue by juandelacruz23** [okta/samples-aspnetcore#22]
Running the resource server sample through the dotnet cli doesn't open in port 8000, it opens 62707. 
The line at fault is:
https://github.com/okta/samples-aspnetcore/blob/db276cba3bd3171918375fa437b2cba575a2c566/resource-server/okta-aspnetcore-webapi-example/Properties/launchSettings.json#L26
After changing the port to 8000, works as a charm :)

**Comment by laura-rodriguez** [comment]
I've verified and it seems fixed now.
