### ISSUE TITLE
Asp.net core identity with okta as external login provider?

### ISSUE THREAD

**Issue by dazinator** [okta/samples-aspnetcore#26]
For asp.net core applications that use identity (local users table), identity has the ability to use "external login providers" like facebook, google, etc etc - the result is that a user can log in using any of the external login providers, not just their local credentials. 

Is there any sample showing how okta can be used in this way?

**Comment by laura-rodriguez** [comment]
Hi @dazinator, 

I've just added multiple samples in our .NET samples repos which show how to use social login. I hope it helps.

**Comment by laura-rodriguez** [comment]
Fixed by #34
