### ISSUE TITLE
'Implicit Flow' link in README is broken in samples-aspnetcore/resource-server/

### ISSUE THREAD

**Issue by gdnmaximus** [okta/samples-aspnetcore#29]
![image](https://user-images.githubusercontent.com/7044180/59324405-ccd0a480-8cac-11e9-9932-c0fd43101567.png)

**Comment by laura-rodriguez** [comment]
Hi @gdnmaximus, 
Thanks for reporting this issue. We have migrated our doc site recently, and some URLs are having issues. We're working on it now.

**Comment by gdnmaximus** [comment]
Thanks for the quick response, Laura. Just in case if you have the link in hand, please post it as a comment.

**Comment by laura-rodriguez** [comment]
You can visit this link: https://developer.okta.com/docs/guides/implement-implicit/overview/
If it doesn't work you can navigate to Docs>Guides>Implement the implicit flow. I hope this works for you, apologies for the inconvenience.

**Comment by nbarbettini** [comment]
Links are fixed now! Sorry for the inconvenience.
