### ISSUE TITLE
Logout using the sample code is giving 400 bad request error (invalid token)

### ISSUE THREAD

**Issue by adwaitpatankar** [okta/samples-aspnetcore#30]
We are integrating with Okta hosted login with our application. While the login is working perfectly fine, we are facing issues in the Okta logout.

Tried the below sample code in the AccountController.
`[HttpPost]
        public IActionResult SignOut()
        {
            return new SignOutResult(
                new[]
                {
                     OktaDefaults.MvcAuthenticationScheme,
                     CookieAuthenticationDefaults.AuthenticationScheme,
                },
                new AuthenticationProperties { RedirectUri = "/index" });
        }`
On logout, we are getting 400 BAD REQUEST error with reason as invalid token.
The okta developer guide clearly mentions that the "id_token_hint" is a mandatory request parameter. Where as the URI that is getting formed in the browser has this request parameter missing.  Is there any setting that should get the "id_token_hint" to be included automatically in the logout call?

**Comment by adwaitpatankar** [comment]
"okta:OrgUri": "https://<domain>.okta.com/oauth2/<id>",
  // 
  "okta:RedirectUri": "http://localhost:49606/authorization-code/callback",
  "okta:PostLogoutRedirectUri": "http://localhost:49606/"

Okta configs

**Comment by adwaitpatankar** [comment]
URL formed automatically after SignOutResult call

https://{domain}.okta.com/oauth2/{id}/**v1/logout**?**post_logout_redirect_uri**=http%3A%2F%2Flocalhost%3A49606%2Fsignout-callback-oidc**&state**=CfDJ8I4x2xsqYARMl8f85dllT3Sm6edgXXr3vFq8GEsXTtzNhWnj76SNbxsYqe8DE8egUxeipHTfsnHBNisNjOiFmupe2Yba-Ao-HY2FwrhR_1_QFKYykEBBOMOiZiBErSxqTYvciE5fv2ANvijyOrx_gRo&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0

**Comment by laura-rodriguez** [comment]
Hi @adwaitpatankar ,

Your configuration doesn't look correct. Your `OktaDomain` (OrgUri in your example) should not include `/oauth2/{id}`. It should be something like `https://mydomain.okta.com`.
You can follow our guides, which have step-by-step instructions:
Sign users in: https://developer.okta.com/docs/guides/sign-into-web-app/aspnetcore/before-you-begin/
Sign users out: https://developer.okta.com/docs/guides/sign-users-out/aspnetcore/sign-out-of-your-app/

Please try to follow those guides and let me know if it helps.

**Comment by adwaitpatankar** [comment]
Hi Laura,

Thanks for the help. The issue seems to have resolved after doing 2 things:

- Setting the **_OpenIdConnectOptions.Savetokens_** property to true. This resulted in the id_token_hint being correctly set for logout URL.
- Using whitelisted URI path for the **_SignOutCallbackPath_** property
