### ISSUE TITLE
Unsupported https://localhost and 44314 port number

### ISSUE THREAD

**Issue by andliang** [okta/samples-aspnetcore#36]
The following IDP urls in [SignIn.cshtml](https://github.com/okta/samples-aspnetcore/blob/249e8754bff089f8019d76ba98708b13290ef759/social-login/okta-aspnetcore-mvc-example/Views/Account/SignIn.cshtml#L26) do not look correct which results in a 404 error.

1. `https://localhost:44314/Account/SignInWithIdp?idp=@Configuration["okta:GoogleIdp"]`
2. `https://localhost:44314/Account/SignInWithIdp?idp=@Configuration["okta:FacebookIdp"]`

The current port for this web app is hardcoded to 29892 so I do not know where 44314. Also SSL is not enabled so I don't know why https is being used.

**Comment by laura-rodriguez** [comment]
Hi @andliang ,

Thanks for reporting this 💯 . The `launchsettings.json` is missing. I submitted a PR to fix this: https://github.com/okta/samples-aspnetcore/pull/37.
