### ISSUE TITLE
How to run the resource-server in IIS

### ISSUE THREAD

**Issue by gtevans** [okta/samples-aspnetcore#42]
Hi

The resource server example (okta-aspnetcore-webapi-example) currently runs in IIS Express, for production my app runs in IIS. I have tried updating the config to run under IIS however when hitting the action it always returns a 401. 

Can you tell me how to update the config to run the example in IIS? Thanks.

**Comment by gtevans** [comment]
I managed to get this working... An IISReset did the trick :D!

**Comment by laura-rodriguez** [comment]
Hi @gtevans,

I'm glad you got it working! Thanks for letting us know.
